# Use Node.js base image
FROM node:18

# Set working directory inside the container
WORKDIR /app

# Copy only necessary files
COPY index.js .

# Set command to run the app
CMD ["node", "index.js"]

# Expose port 3000
EXPOSE 3000
