
services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: BookingDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mac151203
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./booking_system  
      dockerfile: Dockerfile
    ports:
      - "5136:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:8080

  frontend2:
    build:
      context: ./frontendAdmin
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:8080

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:

